# JWT, assinando tokens com par de chaves RSA:
adotapet.jwt.key-alias=hml-jwt-key-adotapet-backend
adotapet.jwt.key-password=JtCbG4fvZyIi11ygMiqA1K0z

# Autenticacao para o usuario do Swagger:
adotapet.api.swagger.senha-acesso=${ADOTAPET_SWAGGER_SENHAACESSO:adota@hml}
