# JWT, assinando tokens com par de chaves RSA:
adotapet.jwt.key-alias=prd-jwt-key-adotapet-backend
adotapet.jwt.key-password=Ovd6zXDH3p3TgaJ95a7AVwdU

# Autenticacao para o usuario do Swagger:
adotapet.api.swagger.senha-acesso=${ADOTAPET_SWAGGER_SENHAACESSO:adota@prd}
