# Configuracoes de banco de dados:
spring.datasource.url=string_jdbc
spring.datasource.username=username
spring.datasource.password=password

# Porta e uso de SSL no servidor:
server.port=${ADOTAPET_SRV_PORT:8080}
server.ssl.enabled=true
server.ssl.key-alias=dev-ssl-key-adotapet-backend

# JWT, assinando tokens com par de chaves RSA:
adotapet.jwt.key-alias=dev-jwt-key-adotapet-backend
adotapet.jwt.key-password=x49DErj2Lc9Gdt4DE57t6yQY

# Autenticacao de acesso ao servico:
adotapet.api.senha-acesso=adota@dev

# Autenticacao para o usuario do Swagger:
adotapet.api.swagger.senha-acesso=adota@dev
