# AVISO:
# Todos os comentarios e nomes de propriedades com seus valores, presentes nos arquivos .properties, devem ser
# inseridos utilizando caracteres ASCII, sem uso de caracteres acentuados e caracteres especiais, pois, pode haver erro
# durante o install do Maven.

# Nome da aplicacao:
spring.application.name=adotapet-backend

# Versao do projeto no pom.xml:
adotapet.versao=@project.version@

# Profile ativo do Spring:
spring.profiles.active=${ADOTAPET_ENV:local}

# DevTools do Spring (recomendavel a ativacao somente nos profiles local ou dev):
spring.devtools.add-properties=false

# Configuracoes de banco de dados:
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${ADOTAPET_DB_JDBC_URL}
spring.datasource.username=${ADOTAPET_DB_USERNAME}
spring.datasource.password=${ADOTAPET_DB_PASSWORD}
spring.jpa.properties.hibernate.show_sql=${ADOTAPET_DB_SQL_SHOW:false}
spring.jpa.properties.hibernate.format_sql=${ADOTAPET_DB_SQL_FORMAT:false}

# Porta e uso de SSL no servidor:
# *SSl desativado por padrao.
server.port=${ADOTAPET_SRV_PORT:8080}
server.ssl.enabled=${ADOTAPET_SRV_SSL_ENABLE:false}
server.ssl.key-store-type=${ADOTAPET_SRV_SSL_KEYSTORE_TYPE:PKCS12}
server.ssl.key-store=${ADOTAPET_SRV_SSL_KEYSTORE:classpath:keystores/keystore-adotapet-backend.p12}
server.ssl.key-store-password=${ADOTAPET_SRV_SSL_KEYSTORE_PSWD:uHTYdyJP7TzQZidEipAZAV89gBc9R4hi0hHEFZgrXR5oTWFP}

# JWT e assinatura dos tokens com par de chaves RSA:
# *Expiracao do token definida em 15 minutos.
adotapet.jwt.expiracao-milisegundos=${ADOTAPET_JWT_EXP_MILISEC:900000}
adotapet.jwt.key-store=keystores/keystore-adotapet-backend.jks
adotapet.jwt.key-store-password=pFqYc4v6SD6XMpl5EeOJF3JA7umP57CWbGp55GvFZAweHRGH

# Autenticacao de acesso ao servico:
adotapet.api.nome-acesso=api.adotapet@estacio.br
adotapet.api.senha-acesso=${ADOTAPET_API_SENHAACESSO}

# Autenticacao para o usuario do Swagger:
adotapet.api.swagger.nome-acesso=swagger.adotapet@estacio.br

# Ordenar o Swagger UI alfabeticamente
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha

# Caminho customizado do swagger-ui
springdoc.swagger-ui.path=/swagger-ui.html
