### Verifica se a aplicação está online e obtém informações da API
GET https://localhost:8080/api/info


### Obter um token de autenticação
POST https://localhost:8080/autenticacao/login
Content-Type: application/json

{
  "email": "fcsalcantara@gmail.com",
  "senha": "Asdf1234."
}


### Criação de usuário
POST https://localhost:8080/usuario/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJ1c2VybmFtZUBlc3RhY2lvLmJyIiwibmJmIjoxNzgwMzI2OTAzLCJpYXQiOjE3ODAzMjY5MDMsImV4cCI6MTc4MDMyOTYwM30.T6JLUXQJCFHzR9u3Cpm2xnoXOvfOxyIoTsY-EGeMNcE_Gzk32P2JXhuoUlwKwnL56WSIfa7atPK1U_cpQxs-drIPHSmjGTfoyd7SBungmxlqTFGrSHVFd5ejLcB38ys9G4wN70TGKcr36gRD4-3hr0ldiVvJx0-G8vZchF8_0yUUVnYABJQeAs5GCjGl_u3fY3PSw9DMxQtuLycPtuCTmU5Lu5guUHv2b4zu5zsJZs6VKhVskriehR5wCy6M1ugWkwbfIzwF1Yoj0xt-g1zRPnIY3sjBEkf1gF7mWu_sSDynHl_0u8qD56QX_UL7jMh9zFDAFUEvR91IOTsxwsOVMclq3c0wsvl-VCgIraU3N2TgP7e_3HewbVZUS3lYBJIRz62k2VmD6CsNwYJVjuwQWTRVwwVNcBHv5UrmeQDz2JiQWpV3FMVSNdHkMT2X9fLJfwEyKbmKplX0DSm3YmTvhvzMo5BKa_o8I1NyPnjStj9mHx0cZe0yfbIE3OAG_vCcVD4bFl3PdSiJS_YvismCf5gExIP3pa6rHYybi_F9yE5PKJfXFVMozWBVf7g9-xaYtN8fwuudmaZfslUw-cdYqDgj6uNWONkmzvbrRAsOA88vfey_qHzuBySKfjxsakTuD5jUi4hVDNocy1G9FgtG6FPOLABvs0fDfV99veOgmF4

{
  "nome": "Flávio Alcântara",
  "email": "fcsalcantara@gmail.com",
  "senha": "Asdf1234.",
  "cpf": "11122233344",
  "telefone": "21976241787"
}


### Obter os dados do usuário
GET https://localhost:8080/usuario/read
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgwMzI3NzU1LCJpYXQiOjE3ODAzMjc3NTUsImV4cCI6MTc4MDMzMDQ1NX0.X0rCV12Q2yZ1BOzAMeFEegCK_sO-WU1WL_TMAgmJ-hqLz3K4_MetiOJ-1-nQN991ML3-wLK9Yg3rLdecIZE38JjbP1OzFg-g9JksL5fvOW7Q5K-53TIZSx-iYbuLD1Y1zqKMU43kj6b8biY02HvGe-EooSXkXa1g5pfCJCJ1-rBV2_K7Nw6DVPL6_yJmcFkSEY3gXic2hHhSRV1n5gx6vN4MhRbLRtC4jojhzLias_054uhZoXHlQ-5-cpzRuyOqyLqBqvFitQJmvU0-6AFWY-cSC0mCNv9-l4S21CyBCahZ--562AY1JkG3cfop_VMGfV4FOvbO0wEwOKHgy2QRUhf1f8UEEK5lJEq5brbnw5Jc6N6PHm8v_Nr1CUptllxIXBdcC91WKv0qnqijHOw5USvLqDYmSSHo4jidMvEZDFeyQ7VMfKSxaCXilG7Zt8a7NC7TOwP-PGw_nsD8HX-MWmS0fCJq17Tj0u7EVUfL5rkDz-ot0DppvJPFk4_2tqsiaqRVletdnRHR6n0Evv16n4ze-GFb0DPh5UJaRvEhBt50Nf9ulIDmWA4S_XuKGmFwQNG3NDcjMWzeCl5u_4jOfL7Yx0aU4n596Sc01UoKGMMtN16xuiD1vn-JrStdAt27Fm2UCenBMoTOb124l3mMe9R4Bwjr6mQ9xSqkE51lSZA


### Atualização de usuário
PATCH https://localhost:8080/usuario/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgwNDAzNDk4LCJpYXQiOjE3ODA0MDM0OTgsImV4cCI6MTc4MDQwNjE5OH0.Rip87DhC709edNit5jjDGpyRJComnOcQ4eMsudRecsm22p651ftJdxBGEiKnIjz3KJD0NvW4u13IUaRJb4KfXjOM3qhiZklIGNNbluBoTBUn64O0PUIC8eRr1bKNVQX2vjBzwhurjyGBKDmYC7jctYtfqniClFziL5IMMCLmTfOMLivIEfCPRF6-EyRpjf_hKKaNLKWJVanaKhTFAiNK3pdRKGtPO4inudxfr2hkb3AhAEnmVZYcbnGAGW_3cCJysK6GYTYPYp_FBUGXTz6IpSjb-5MJGIBWiwUlOBHnfG_PY8doGx-gDiRsdR5spxotNU0v9p1pZLARls8wLWSHr4RoX7h7uFDghG6MCM_9C4-d2MBdy-73Y-AlHbIo94-vknv09tMAHZyNkR0TD4_tcJTV7Nm_I6EyKCrg7W9iZ0wNpjweR1NjkCWEuGUSqMRp6Kzt4iRQlDXZ_9uVvN1fBCbw2U9uTj9KdXjKz1OsQbKJDdZaKSKCw9O_napbJDI5zZBDO_gZdlVU5OQmO4Bm8Jgxi4OO2ujJzDvWDCFeyttB1_G2yFbdgFkfbRrUCe1zthgcUnMSUY6IBstD3yaaU-IYS2YP6ZOZ6CzwFFJRQ44IFWBS1Tl2L6OOTNZelKyqDx4DEZsEkX5Q2ukD9r6f0PBs_pSWSm50ZWhWUhxV6U8

{
  "id": 3,
  "nome": "Flávio C. S. de Alcântara",
  "email": "",
  "telefone": "21994034111"
}


### Exclusão de usuário
@id = 3
DELETE https://localhost:8080/usuario/delete{{id}}
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgwNDAzODk2LCJpYXQiOjE3ODA0MDM4OTYsImV4cCI6MTc4MDQwNjU5Nn0.V4HxGIrM0RcspOTgwm9eQHZmZIHoIreWGOuERlQsFo8b8bxcvpniqMeSHD7ncy0nm8ddfHM1qXBTPsBgwetXsSdgTZYyxMRbrP1visg6WJltsnYw75EGNDcQZEt0JWWZ3XfEZkY8Jrkh-y3dPBFWCARcUwNgzGEWqQ00MceiY3XIs0uvfALfz5oy-WvZCj52q2-4_Y4ONG5OL7mYXpTOCTVlLn3odad_0xaMuHEHK3AHygLXj5HZ8PzaD2RKKOdgglb8EkAkSPqIOaIki8_hPNruuTbTgxpGlXHP_DoFQ9XKkgpLoW0cUTYYLU7KJ6npHUGJgfVY_UN3pQ99C4oZ4eE5VgsQ8yGaxOV-FAh6jrpyzgn4scpsg3iTatDpcywKBA1ZGQl6nNScJsM-X48gl9m2Wn7r689q3Yt5-9Xc-Rh-KwZh5txNLHXk8A0D7U1RT1KHCS15rsqXSMK69gb2IK2_lt-ti7749mqV7xlV8gA-ImbfH1F5TXWEJUiEaAc3HiZZwQ1xVItVCoh18Ab_dSLJvbHViKNhTYcbgaAa-XKvWN7JuzveuX5jbR4ga40d711zHE-KxSj6own10fxrUbbeB7s6f9_F1ngt-bn-R7hPpaDviWZuPdlXDyT8PTUNp7mZ4dSuW1wYqnwFuCdPSrqthDjOw59VeJH7-7c4yT4
