### Verifica se a aplicação está online e obtém informações da API
GET https://localhost:8080/api/info


### Obter um token de autenticação
POST https://localhost:8080/autenticacao/login
Content-Type: application/json

{
  "email": "username@estacio.br",
  "senha": "adota@local"
}


### Criação de usuário
POST https://localhost:8080/usuario/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJ1c2VybmFtZUBlc3RhY2lvLmJyIiwibmJmIjoxNzgxMTE4NjIxLCJpYXQiOjE3ODExMTg2MjEsImV4cCI6MTc4MTEyMTMyMX0.XBvZ8Ja25RpDYam6ddOTSyf_F2F4naAqykxOdwv5tia-RZqM2XLLWfeiSUafzavNut1e24cc2bqRGPwSrV0oKgqtrevSwL0f39VRxem87nrvNXB6ZJsdZv-wMilUVdQ9Kl-d0WIDtdTqbroN5Fcu_-6b5vvQtcmR3YX9261oHaNaAG3pO9nXKOJkS4BDYpXiy-0Tnt3wAraAspTIwPZhQtJQTdBPSHfhxRe45F2v4NcHf9LADANbMSEJPa82A7hoPl63LXL3V6xprmHQY9q5KQ6L0K9eSI3sVBN0IUTHDRybQ9ZPek8EWNb2R5dGFlR04Jr7y0vCtpngz90trpeozIlNL-8SIauLKIQHs9M06u9GUh2Z0rFh_oAfoWzNJHfkIsmQ710CKvz4qFQyp_Gw1xXLOIjfpjCoyKnirkZ1VFUqDfpkTS7KJv8F62AphrsB3_9N6rAwgz-olh204ikSbI7lZHYA3uPm2FjkYhYoIJYKVDmLllWIXlw-JNmXMODTGQsMfmuYM3ghS9bPw8AKml7pIBT-hAwk_zgymdBtnK8L2UTuTebNAfUVZe7_07z8AuKg8ZC9aLIDgBW6yIFzphyr11M-5ecTRFdnRw5Lnuuq6tlYjEdIQNVhoUjcolYlPUnjJ_axSoPyIF2S6CPYjEetDf0mu8rQ8pgBjp-hy6c

{
  "nome": "Flávio Alcântara",
  "email": "fcsalcantara@gmail.com",
  "senha": "Asdf1234.",
  "cpf": "11122233344",
  "telefone": "21976241787"
}


### Obter os dados do usuário
GET https://localhost:8080/usuario/read
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgxMTE4NjQwLCJpYXQiOjE3ODExMTg2NDAsImV4cCI6MTc4MTEyMTM0MH0.O93_Zz4Uf65XPHNgH99bzcGmTivie70iTFZWLGtRg5LXvA1Gg8O3eTfPsXQlTjBEGWHCmXtOBnJrTk4aldMZvd2hl2sildrDMhR6OwI5985ncPh7jU9gXzTvPdR21RhDRZnrJzq6SPE0vGw653GBPQogSPzMlGjvt9BqY5WpvJaV55lLc_BpzXBPc40oKPSnuAjHgFQaQtk-U9BTD1l9c__DlrDgz_rHOO3f68ACe18iHyNa-mDdRXKf6UrL_OQ1TvLEl-hn9jr1CkSs3n5sDm2H0Ge3DMjvSYVnV71LuzTE-0XXj3sQxjdldgat5eHhK0yN5Wc5pFfiKEN-78RkECZQx5xUn3bdxrzGJqupUbn6ZraKvYvbe3equA9OMk7qo57NXXjI0gf0GiPns9h2CVBZVSx1UKntq7PQ_N-DKQS4MSCoYArolk-5ceiHiPqzFIryPKvRKXKRCDNh2DiwicKqUhv94e1sYDqLiGkpgzCEaL3KrZENz-HzlBJouCmstKQ7fXrnfIm_kV6Hk7Ysrdl1wNCHH3oBcvDxlaCBWfjPaeQhEqeFXuN5MpXDAmF77Uc9Qy0Q3DnUICNYof4IOMWRfOhAdiHYZBXuTrnG5tnuirtc202jEf2WJBYjo7F4tNOOSle5aZmPdA2ook1Hp7jJH5BbpdxYrumokMFqe4M


### Atualização de usuário
PATCH https://localhost:8080/usuario/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgxMTE4NjQwLCJpYXQiOjE3ODExMTg2NDAsImV4cCI6MTc4MTEyMTM0MH0.O93_Zz4Uf65XPHNgH99bzcGmTivie70iTFZWLGtRg5LXvA1Gg8O3eTfPsXQlTjBEGWHCmXtOBnJrTk4aldMZvd2hl2sildrDMhR6OwI5985ncPh7jU9gXzTvPdR21RhDRZnrJzq6SPE0vGw653GBPQogSPzMlGjvt9BqY5WpvJaV55lLc_BpzXBPc40oKPSnuAjHgFQaQtk-U9BTD1l9c__DlrDgz_rHOO3f68ACe18iHyNa-mDdRXKf6UrL_OQ1TvLEl-hn9jr1CkSs3n5sDm2H0Ge3DMjvSYVnV71LuzTE-0XXj3sQxjdldgat5eHhK0yN5Wc5pFfiKEN-78RkECZQx5xUn3bdxrzGJqupUbn6ZraKvYvbe3equA9OMk7qo57NXXjI0gf0GiPns9h2CVBZVSx1UKntq7PQ_N-DKQS4MSCoYArolk-5ceiHiPqzFIryPKvRKXKRCDNh2DiwicKqUhv94e1sYDqLiGkpgzCEaL3KrZENz-HzlBJouCmstKQ7fXrnfIm_kV6Hk7Ysrdl1wNCHH3oBcvDxlaCBWfjPaeQhEqeFXuN5MpXDAmF77Uc9Qy0Q3DnUICNYof4IOMWRfOhAdiHYZBXuTrnG5tnuirtc202jEf2WJBYjo7F4tNOOSle5aZmPdA2ook1Hp7jJH5BbpdxYrumokMFqe4M

{
  "id": 3,
  "nome": "Flávio C. S. de Alcântara",
  "email": "",
  "telefone": "21994034111"
}


### Exclusão de usuário
@id = 3
DELETE https://localhost:8080/usuario/delete{{id}}
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgwNDAzODk2LCJpYXQiOjE3ODA0MDM4OTYsImV4cCI6MTc4MDQwNjU5Nn0.V4HxGIrM0RcspOTgwm9eQHZmZIHoIreWGOuERlQsFo8b8bxcvpniqMeSHD7ncy0nm8ddfHM1qXBTPsBgwetXsSdgTZYyxMRbrP1visg6WJltsnYw75EGNDcQZEt0JWWZ3XfEZkY8Jrkh-y3dPBFWCARcUwNgzGEWqQ00MceiY3XIs0uvfALfz5oy-WvZCj52q2-4_Y4ONG5OL7mYXpTOCTVlLn3odad_0xaMuHEHK3AHygLXj5HZ8PzaD2RKKOdgglb8EkAkSPqIOaIki8_hPNruuTbTgxpGlXHP_DoFQ9XKkgpLoW0cUTYYLU7KJ6npHUGJgfVY_UN3pQ99C4oZ4eE5VgsQ8yGaxOV-FAh6jrpyzgn4scpsg3iTatDpcywKBA1ZGQl6nNScJsM-X48gl9m2Wn7r689q3Yt5-9Xc-Rh-KwZh5txNLHXk8A0D7U1RT1KHCS15rsqXSMK69gb2IK2_lt-ti7749mqV7xlV8gA-ImbfH1F5TXWEJUiEaAc3HiZZwQ1xVItVCoh18Ab_dSLJvbHViKNhTYcbgaAa-XKvWN7JuzveuX5jbR4ga40d711zHE-KxSj6own10fxrUbbeB7s6f9_F1ngt-bn-R7hPpaDviWZuPdlXDyT8PTUNp7mZ4dSuW1wYqnwFuCdPSrqthDjOw59VeJH7-7c4yT4


### Criação de novo animal
POST https://localhost:8080/animal/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgxMTE4NjQwLCJpYXQiOjE3ODExMTg2NDAsImV4cCI6MTc4MTEyMTM0MH0.O93_Zz4Uf65XPHNgH99bzcGmTivie70iTFZWLGtRg5LXvA1Gg8O3eTfPsXQlTjBEGWHCmXtOBnJrTk4aldMZvd2hl2sildrDMhR6OwI5985ncPh7jU9gXzTvPdR21RhDRZnrJzq6SPE0vGw653GBPQogSPzMlGjvt9BqY5WpvJaV55lLc_BpzXBPc40oKPSnuAjHgFQaQtk-U9BTD1l9c__DlrDgz_rHOO3f68ACe18iHyNa-mDdRXKf6UrL_OQ1TvLEl-hn9jr1CkSs3n5sDm2H0Ge3DMjvSYVnV71LuzTE-0XXj3sQxjdldgat5eHhK0yN5Wc5pFfiKEN-78RkECZQx5xUn3bdxrzGJqupUbn6ZraKvYvbe3equA9OMk7qo57NXXjI0gf0GiPns9h2CVBZVSx1UKntq7PQ_N-DKQS4MSCoYArolk-5ceiHiPqzFIryPKvRKXKRCDNh2DiwicKqUhv94e1sYDqLiGkpgzCEaL3KrZENz-HzlBJouCmstKQ7fXrnfIm_kV6Hk7Ysrdl1wNCHH3oBcvDxlaCBWfjPaeQhEqeFXuN5MpXDAmF77Uc9Qy0Q3DnUICNYof4IOMWRfOhAdiHYZBXuTrnG5tnuirtc202jEf2WJBYjo7F4tNOOSle5aZmPdA2ook1Hp7jJH5BbpdxYrumokMFqe4M

{
  "nome": "Melody",
  "tipo": "CAO",
  "sexo": "FEMEA",
  "idade": 11,
  "porte": "PEQUENO",
  "foto": "...",
  "descricao": "Cão Teckel preto.",
  "usuarioId": 1
}


### Obtém lista de animais cadastrados
GET https://localhost:8080/animal/read
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgxMTE4NjQwLCJpYXQiOjE3ODExMTg2NDAsImV4cCI6MTc4MTEyMTM0MH0.O93_Zz4Uf65XPHNgH99bzcGmTivie70iTFZWLGtRg5LXvA1Gg8O3eTfPsXQlTjBEGWHCmXtOBnJrTk4aldMZvd2hl2sildrDMhR6OwI5985ncPh7jU9gXzTvPdR21RhDRZnrJzq6SPE0vGw653GBPQogSPzMlGjvt9BqY5WpvJaV55lLc_BpzXBPc40oKPSnuAjHgFQaQtk-U9BTD1l9c__DlrDgz_rHOO3f68ACe18iHyNa-mDdRXKf6UrL_OQ1TvLEl-hn9jr1CkSs3n5sDm2H0Ge3DMjvSYVnV71LuzTE-0XXj3sQxjdldgat5eHhK0yN5Wc5pFfiKEN-78RkECZQx5xUn3bdxrzGJqupUbn6ZraKvYvbe3equA9OMk7qo57NXXjI0gf0GiPns9h2CVBZVSx1UKntq7PQ_N-DKQS4MSCoYArolk-5ceiHiPqzFIryPKvRKXKRCDNh2DiwicKqUhv94e1sYDqLiGkpgzCEaL3KrZENz-HzlBJouCmstKQ7fXrnfIm_kV6Hk7Ysrdl1wNCHH3oBcvDxlaCBWfjPaeQhEqeFXuN5MpXDAmF77Uc9Qy0Q3DnUICNYof4IOMWRfOhAdiHYZBXuTrnG5tnuirtc202jEf2WJBYjo7F4tNOOSle5aZmPdA2ook1Hp7jJH5BbpdxYrumokMFqe4M


### Obtém dados de um animal cadastrado
GET https://localhost:8080/animal/read/6
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrZW5kLmFkb3RhcGV0LmVzdGFjaW8uYnIiLCJzdWIiOiJmY3NhbGNhbnRhcmFAZ21haWwuY29tIiwibmJmIjoxNzgxMTE4NjQwLCJpYXQiOjE3ODExMTg2NDAsImV4cCI6MTc4MTEyMTM0MH0.O93_Zz4Uf65XPHNgH99bzcGmTivie70iTFZWLGtRg5LXvA1Gg8O3eTfPsXQlTjBEGWHCmXtOBnJrTk4aldMZvd2hl2sildrDMhR6OwI5985ncPh7jU9gXzTvPdR21RhDRZnrJzq6SPE0vGw653GBPQogSPzMlGjvt9BqY5WpvJaV55lLc_BpzXBPc40oKPSnuAjHgFQaQtk-U9BTD1l9c__DlrDgz_rHOO3f68ACe18iHyNa-mDdRXKf6UrL_OQ1TvLEl-hn9jr1CkSs3n5sDm2H0Ge3DMjvSYVnV71LuzTE-0XXj3sQxjdldgat5eHhK0yN5Wc5pFfiKEN-78RkECZQx5xUn3bdxrzGJqupUbn6ZraKvYvbe3equA9OMk7qo57NXXjI0gf0GiPns9h2CVBZVSx1UKntq7PQ_N-DKQS4MSCoYArolk-5ceiHiPqzFIryPKvRKXKRCDNh2DiwicKqUhv94e1sYDqLiGkpgzCEaL3KrZENz-HzlBJouCmstKQ7fXrnfIm_kV6Hk7Ysrdl1wNCHH3oBcvDxlaCBWfjPaeQhEqeFXuN5MpXDAmF77Uc9Qy0Q3DnUICNYof4IOMWRfOhAdiHYZBXuTrnG5tnuirtc202jEf2WJBYjo7F4tNOOSle5aZmPdA2ook1Hp7jJH5BbpdxYrumokMFqe4M
